Repository bazelruby/rules_ruby, pull requests merged in 2019-12, with the labels that each got.

#17 Make ruby_binary compatible with container
  .travis.yml
  WORKSPACE
  examples/simple_script/.rspec
  examples/simple_script/BUILD
  examples/simple_script/spec/script_spec.rb
  ruby/private/BUILD.host_runtime.tpl
  ruby/private/binary.bzl
  ruby/private/binary_wrapper.tpl
  ruby/private/bundle/create_bundle_build_file.rb
  ruby/private/host_runtime.bzl
  ruby/private/toolchain.bzl
  ruby/private/tools/deps.bzl
  ruby/tests/BUILD.bazel
  ruby/tests/container_test.sh
  ruby/tools/init_loadpath.rb
Labels: ready-for-review

#22 Run ruby_binary with the interpreter in a SDK again
  ruby/private/binary.bzl
  ruby/private/binary_wrapper.tpl
Labels: ready-for-review

#28 Expose rake, erb and other commands as sh_binary
  Gemfile.lock
  ruby/private/BUILD.host_runtime.tpl
  ruby/private/host_runtime.bzl
  ruby/tests/BUILD.bazel
  ruby/tests/diff_test.rb
  ruby/tests/testdata/BUILD.bazel
  ruby/tests/testdata/bundled_commands/erb_golden
  ruby/tests/testdata/bundled_commands/erb_input
  ruby/tests/testdata/bundled_commands/irb_golden
  ruby/tests/testdata/bundled_commands/irb_input
  ruby/tests/testdata/bundled_commands/rake_golden
  ruby/tests/testdata/bundled_commands/rake_input
Labels: —— milestone 0.1 ——

#30 Fixing Gemfile bundle dependency and bin/setup
  bin/setup
Labels: —— milestone 0.1 ——

#32 Add `files` to DefaultInfo of the ruby_library
  ruby/private/library.bzl
Labels: ready-for-review

#35 Sight facelift to shell files:
  .gitignore
  .rules_version
  README.md
  bin/deps
  bin/setup
  bin/setup-darwin
  bin/setup-linux
  docs/faq.md
  docs/img/ruby_rules.png
  docs/rules_ruby_architecture.md
  docs/troubleshooting.md
  ruby/private/bundle/bundle.bzl
Labels: ready-for-review, —— milestone 0.1 ——

#38 [Fix] no spaces in files bug, remove deprecated code, remove host
  .gitignore
  examples/simple_script/Gemfile
  examples/simple_script/README.md
  examples/simple_script/WORKSPACE
  examples/simple_script/script.rb
  ruby/private/binary.bzl
  ruby/private/binary_wrapper.tpl
  ruby/private/bundle/bundle.bzl
  ruby/private/bundle/create_bundle_build_file.rb
  ruby/private/toolchain.bzl
  ruby/private/toolchains/BUILD.runtime.tpl
Labels: ready-for-merge

#39 Adding CircleCI + upgrade Rubocop
  .circleci/.bazelrc
  .circleci/Dockerfile
  .circleci/build.sh
  .circleci/config.yml
  .env
  .gitignore
  .rubocop.yml
  .travis.yml
  Gemfile
  Gemfile.lock
  README.md
  bin/ci
  bin/setup-linux
  examples/simple_script/BUILD
  ruby/tests/container_test.sh
Labels: ready-for-review

#48 Deprecate ruby/def.bzl + spelling + v0.1.2
  .rules_version
  ruby/def.bzl
  ruby/tests/BUILD.bazel
Labels: feature

#56 Fixing brittle Host Ruby version detection.
  ruby/private/toolchains/ruby_runtime.bzl
Labels: ready-for-review, rule::ruby_sdk, —— milestone 0.1 ——
